{% set name = "ttkwidgets" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b1d69dffebef1820ee46b244469913d1911a563a15bb9b0823c71c950daead7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - ttkwidgets
  requires:
    - pip
    - xorg-libx11
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://pypi.org/project/ttkwidgets/
  summary: A collection of widgets for Tkinter's ttk extensions by various authors.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://ttkwidgets.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - marcodomingues99
